### ISSUE TITLE
logfile format is undocumented

### ISSUE THREAD

**Issue by sam-github** [containerd/cri#1339]
Or at least, I  can't find the documentation for it.

It's CRI specific:
- https://github.com/containerd/cri/blob/0dcaf6e98719b02ad9a1cf93aa3c7dcb4225f7fc/pkg/server/io/logger.go#L49-L50

I found an example of it in an old PR comment:
- https://github.com/containerd/cri/pull/421/files#r152399214

But no other information.

The "tag" in particular ("P"? "F"?) I'm not sure what it indicates.

I have been searching for the source of that CRI format, because its turning my container's JSON-per-line output into invalid JSON (see https://github.com/ubuntu/microk8s/issues/803#issuecomment-554680594).

It doesn't appear to be opt-out, which I assume is for good reason, but the lack of docs made it quite hard to find who was responsible for the log decoration (fluentd, microk8s, kubelet, systemd, journald, snap, and containerd, were all options I searched through, until I found that PR comment).

**Comment by Random-Liu** [comment]
The CRI format documentation is here https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/kubelet-cri-logging.md.

**Comment by sam-github** [comment]
Thanks @Random-Liu I see you are the author of 
 https://github.com/kubernetes/kubernetes/commit/70a0cdfa8e05ac47d7dd04b032ceb79bead3fb5f 

That change doesn't work for me when `<log>` is itself JSON, it is just finding the text, and it shows up in elastic search as a string log message, with the string content being JSON, something like `{"level": "info", ...etc}`

Its my understanding that fluentd needs to know here at time of ingest that the `log` is JSON, as it does in the first branch of the multiformat, the original one that expected each line to consist of only JSON.

Am I missing something? Is there a later stage in the pipeline where container output can be parsed into JSON, maybe in elastic search?

**Comment by sam-github** [comment]
https://github.com/kubernetes/kubernetes/pull/54777 <-- to link these issues

**Comment by Random-Liu** [comment]
@sam-github If your log content is json, it will just be streamed as json, I don't think we configure fluentd to parse the actual log content today.

To us, it is container output, we'll stream it as it is.

**Comment by sam-github** [comment]
> If your log content is json, it will just be streamed as json,

it will have have the CRI log format metadata prepended, making it non-json

> I don't think we configure fluentd to parse the actual log content today.

its parsed here:

https://github.com/kubernetes/kubernetes/blob/c97baa339b5043424522dc7932fc3891f15543cb/cluster/addons/fluentd-elasticsearch/fluentd-es-configmap.yaml#L123-L125

that configuration would parse my log output:

> { "level": 30, "time": 1573102855098, "pid": 28461, "hostname": "samtu", "name": "from-PINO", "req": { "id": 1, "method": "GET", "url": "/", "headers": { "host": "localhost:3000", "user-agent": "curl/7.64.0", "accept": "*/*" }, "remoteAddress": "::ffff:127.0.0.1", "remotePort": 46692 }, "res": { "statusCode": 200, "headers": { "x-powered-by": "Express", "content-type": "text/html; charset=utf-8", "content-length": "170", "etag": "W/\"aa-z+ebXSEdArbZ+EXlN/WQjf6HV8c\"" } }, "responseTime": 170, "msg": "request completed", "v": 1 }

Or see the json format docs, https://docs.fluentd.org/parser/json, for a [smaller example](https://docs.fluentd.org/parser/json#example), and notice how all the keys are parsed out (`"method": "PUT"`, for example).

but the json parser won't match the input once the CRI data is prepended.

The fallback parser, https://github.com/kubernetes/kubernetes/blob/c97baa339b5043424522dc7932fc3891f15543cb/cluster/addons/fluentd-elasticsearch/fluentd-es-configmap.yaml#L127-L130, does sucessfully match the CRI metadata, but it treats the log message as unstructured text (unlike how the JSON parser would [load it](https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/parser_json.rb)).

I don't see any way to next parser plugins in fluentd, to use a regex to match, then take the `log` part, and pass it to a sub-parser.

AFAICT, this means there needs to be a CRI plugin written, that checks the `log` part of the CRI format, and applies the JSON parser logit to it if it's JSON, and does what it does now with the regex parser if its non-json. And if its a series of `key=value` pairs... or [apache](https://docs.fluentd.org/parser/apache2) ... I don't know. Its not clear to me how this is supposed to used. The CRI format clearly works as an internal data format shared with kubelet/`kubectl log`, but how to consume it with fluentd isn't clear.

**Comment by Random-Liu** [comment]
```
{
  "timestamp": "xxxx",
  "stream": "stdout",
  "message: "Your escaped json log",
}
```

Before CRI log format is introduced, here is the docker log format. Are you saying that fluentd is going to parse "your escaped json log"? I never tried it, but I thought it wouldn't

**Comment by sam-github** [comment]
Yes, I am saying that, Not from direct experience. I started post-containerd, but posts below claim that it used to work:

- https://github.com/fluent/fluentd/issues/2021
- https://github.com/fluent/fluentd/issues/2073

They claim that such nested JSON was indeed parsed, then was broken for a while (by fluentd). Its not clear why those issues were closed, They each say they were fixed but they just point to the other as the fix, which is infinitely circular. I don't have access to a non-containerd microk8s to try to see pre and post CRI annotation behaviour. I'll try to work through the config examples in those issues, and identify the fluentd versions they apply to, and compare to the one I got with kube/microk8s 1.13.

Its not entirely clear to me where the responsibility for setting this up lies, maybe its all on me to configure fluentd to parse containerd output?

I originally thought it was the ubuntu microk8s snap team that had a config that didn't cover this case, but it looks to me that containerd and kube and fluentd are all CNCF and ubuntu just packages the default configuration. Then issues like above make it look like JSON logs used to work with no mods to the default config with docker JSON. As well, I keep finding posts indicating that some effort has gone in, credit to you, to ensure that the es-fluentd addon parses CRI logs with default config.

**Comment by voltairevi** [comment]
Hi @sam-github, did you manage to get this working?

**Comment by sam-github** [comment]
No, never had enough time to figure out how fluentd can somehow redirect a sub-string to the JSON parser, and since it only affects microk8s on my laptop, playing around mode, its not so critical for me to get it working, cloud deployments do things differently.

**Comment by Sieabah** [comment]
This is still an issue with fluentd and it seems judging by the age of some of their issues regarding this they have no intention to fix it.

[From another thread, the solution is to double parse the logs](https://github.com/fluent/fluentd/issues/2073#issuecomment-747201456), however how many times you need to parse is unknown and different formatters may/may not work.

**Comment by sam-github** [comment]
Is the format documented now?
